name: Vue build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Set global environment variables:
    - name: set global env
      id: global_env
      run: |
        echo "::set-output name=IMAGE_NAME::${GITHUB_REPOSITORY#*/}"
        echo "::set-output name=DOCKERHUB_IMAGE_NAME::ghcr.io/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}"
    # Build Docker image:
    - name: Build and tag image
      run: |
          docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .
    - name: Log into registry
      # This is where you will update the PAT to GITHUB_TOKEN
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Publish image to github package repository:
    - name: Publish image
      env:
        IMAGE_NAME: $GITHUB_REPOSITORY
      run: docker push "ghcr.io/$GITHUB_REPOSITORY/${{ steps.global_env.outputs.IMAGE_NAME }}"

  pull:
    # Ensure test job passes before pushing image.
    needs: build

    runs-on: ubuntu-latest
    
    steps:
      - uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          
      - uses: Azure/k8s-deploy@v1.4
        with:
          action: deploy
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
          images: |
            ghcr.io/eat-it-team/log-final-front/log-final-front:latest
